### ISSUE TITLE
Add postinstall script

### ISSUE THREAD

**Issue by janmichek** [aeternity/ga-multisig-contract#16]
I think this post-install should be part of github:aeternity/ga-multisig-contract similar to https://github.com/aeternity/aeternity-fungible-token/blob/master/.scripts/postinstall.js

_Originally posted by @thepiwo in https://github.com/aeternity/multisig-user-demo/pull/1#discussion_r885253772_

**Comment by thepiwo** [comment]
Should I implement this?

**Comment by janmichek** [comment]
@thepiwo As you wish... I don't have edit permissions to the repo eighter way

**Comment by thepiwo** [comment]
feel free to fork it and create a PR that way

**Comment by janmichek** [comment]
Got it, I am keeping this on list, but there are some more serious issues. Will come to this

**Comment by janmichek** [comment]
Forked, edited requested for pull. I have accomadated changes to user demo from my form and it works nice
