### ISSUE TITLE
Unexpected proposal revoke

### ISSUE THREAD

**Issue by ifaouibadi** [aeternity/ga-multisig-contract#30]
Create a vault with 5 signers, 2 no of confirmation required.
if 2 signers refuse proposal is getting internal revoke while it should stay active cause we still have 3 signers that can approve it

```
stateful function refuse_and_revoke(tx: transaction) =
    put(state{ current_tx = Some(tx) })
    Chain.event(TxRefused(tx.tx_hash, Call.caller))
    if(state.confirmations_required == Set.size(tx.refused_by)) # <= should be: (Set.size(state.signers) - Set.size(tx.refused_by)) < state.confirmations_required
      internal_revoke(tx.tx_hash)
```

**Comment by marc0olo** [comment]
not sure if this is a bug. this is what we have discussed initially, that the revocation is triggered automatically.

I mean in this state it could be revoked, right? we need 2 confirmations. 2 people revoked -> tx will be removed

cc @thepiwo

**Comment by kenodressel** [comment]
I agree, otherwise when we have a 2 out of 1000 multisig, we would need 998 accounts to refuse the tx?

**Comment by subhod-i** [comment]
We could maintain 2 decision parameters for fine control.
1. approval_confirmations_required
2. refuse_confirmations_required

If we set approval to 2 and refuse to 2 out of 5 signers, then whichever meets the criteria first that action could be performed. It could also be implemented with just one variable in the smart contract as we have right now but having 2 will also improve smart contract readability.

**Comment by subhod-i** [comment]
> not sure if this is a bug. this is what we have discussed initially, that the revocation is triggered automatically.
> 
> I mean in this state it could be revoked, right? we need 2 confirmations. 2 people revoked -> tx will be removed
> 
> cc @thepiwo

Agreed. First come first out action.

**Comment by marc0olo** [comment]
> If we set approval to 2 and refuse to 2 out of 5 signers, then whichever meets the criteria first that action could be performed. It could also be implemented with just one variable in the smart contract as we have right now but having 2 will also improve smart contract readability.

any reason for that except "UX" ?

**Comment by ifaouibadi** [comment]
> any reason for that except "UX" ?

Thank you @marc0olo and @kenodressel for clarifying the purpose of `confirmations_required`. I will work with the design team to update the descriptions to clearly indicate that this feature is intended for both confirmation and refusal. that `confirmations_required` it's either for confirm or refuse.
